# Generated by Django 4.1.4 on 2023-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('metaMonto', models.IntegerField()),
                ('metaFecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Materia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('diaEntrega', models.DateTimeField()),
            ],
        ),
    ]
