# Generated by Django 4.1.4 on 2023-09-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RutinaEjercicios',
            new_name='RutinaEjercicio',
        ),
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
