# Generated by Django 3.1 on 2023-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rutinaejercicios_rutinaejercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='movimientos'),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ejemplos'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(null=True, upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
