
pipeline {
    agent any  // Usar cualquier agente disponible en Jenkins
    
    stages {
        stage('Checkout') {
            steps {
                // Clonar el repositorio de código fuente (puede variar según el sistema de control de versiones)
                checkout scm
            }
        }
        
        stage('Instalar dependencias') {
            steps {
                // Instalar las dependencias de Python (por ejemplo, usando pip)
                sh 'pip install -r requirements.txt'
            }
        }
        
        //stage('Build') {
            //steps {
                // Paso para construir tu proyecto
                //sh 'python manage.py'  // Ejemplo de comando de manage.py
            }
        stage('Ejecutar la aplicación de Python') {
            steps {
                // Ejecutar la aplicación de Python
                sh 'python mi_aplicacion.py'  // Reemplaza "mi_aplicacion.py" con el nombre de tu archivo de Python
            }
        }
    }
    
    post {
       success {
            echo 'El pipeline se ejecutó con éxito'
            // Puedes agregar aquí otros pasos que deseas ejecutar en caso de éxito
        }
        failure {
            echo 'El pipeline falló'
            // Puedes agregar aquí otros pasos que deseas ejecutar en caso de fallo
        }
    }
}